# Generated by Django 5.0.1 on 2024-01-24 17:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issues_tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributor",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="contributor",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("project", "user")},
        ),
    ]
